branches:
  only:
  - code

language: node_js

node_js:
  - 10.16.0

before_script:
  - npm install -g gatsby-cli

deploy:
  provider: script
  script: npm install && npm run deploy
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master